name: shopping_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.10.0
  image_picker:
  curved_navigation_bar:
  random_string:
  path:
  mime:
  uuid:
  flutter_stripe:
  http:
  shared_preferences:
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.6




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/



flutter_icons:
  android: true
  ios: true
  image_path: "images/spleshScreen.jpg"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/spleshScreen.jpg"